import "./globals.css";
import Footer from "@/components/footer/page";
import Header from "@/components/header/Header";
import Reactquery from "./Reactquery";
import { Toaster } from "@/components/ui/toaster";
import ContextProvider from "./context/contextProvider";
import Providers from "./progressbar";

export const metadata = {
  title: "Shop App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Reactquery>
        <ContextProvider>
          <body>
            <Providers>
              <Header />
              {children}
              <Toaster />
              <Footer />
            </Providers>
          </body>
        </ContextProvider>
      </Reactquery>
    </html>
  );
}
